# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20170628_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='app_code',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
