# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_app_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=13)),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=13)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=13)),
                ('lowest_price', models.DecimalField(decimal_places=2, max_digits=13)),
                ('highest_price', models.DecimalField(decimal_places=2, max_digits=13)),
                ('app_code', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(auto_now=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('product', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
    ]
