# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_priceflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceflow',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
