# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20170628_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceflow',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
