# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-12 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_priceflow_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('app_code', models.PositiveIntegerField(default=0)),
                ('trade_price', models.DecimalField(decimal_places=2, help_text='\u6210\u4ea4\u4ef7\u683c', max_digits=13)),
                ('trade_time', models.DateTimeField(auto_now=True, null=True)),
                ('create_time', models.DateTimeField(auto_now=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('product', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'db_table': 'product_trade_flow',
            },
        ),
    ]
