# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-12 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_tradeflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeflow',
            name='market_hash_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='market_hash_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='market_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tradeflow',
            name='product',
            field=models.ForeignKey(db_constraint=False, default=0, on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
