# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-12 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20170812_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeflow',
            name='trade_time',
            field=models.DateTimeField(help_text='\u6210\u4ea4\u4ef7\u683c', null=True),
        ),
    ]
