# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-12 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20170812_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('app_code', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=13)),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=13)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=13)),
                ('lowest_price', models.DecimalField(decimal_places=2, max_digits=13)),
                ('highest_price', models.DecimalField(decimal_places=2, max_digits=13)),
                ('trade_date', models.DateTimeField(null=True)),
                ('note', models.CharField(max_length=255, null=True)),
                ('create_time', models.DateTimeField(auto_now=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'db_table': 'product_day_line',
            },
        ),
    ]
